{"name": "Проверка отказа в авторизации из-за данных, под которыми не было регистрации", "status": "passed", "start": 1722200242364, "stop": 1722200242490, "uuid": "5c390349-a3d9-4b51-a86f-4eefe3cb0ff7", "historyId": "b91345ae9677bc29cf47bd977a757b8f", "testCaseId": "b91345ae9677bc29cf47bd977a757b8f", "fullName": "tests.test_login_courier.TestLoginCourier#test_authorization_not_exists_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DTALS"}, {"name": "thread", "value": "12476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}