{"name": "Проверка отказа в авторизации из-за неправильного пароля", "status": "passed", "start": 1722200242276, "stop": 1722200242361, "uuid": "61808fae-f274-48ea-a69a-6ced4265589f", "historyId": "91ca27b5d68dc958e5e36e47a8b892b5", "testCaseId": "91ca27b5d68dc958e5e36e47a8b892b5", "fullName": "tests.test_login_courier.TestLoginCourier#test_authorization_wrong_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DTALS"}, {"name": "thread", "value": "12476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}